name: Checkov IaC Scan

on:
  push:
    branches:
      - main

jobs:
  checkov-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Checkov
        run: pip install checkov

      - name: Verify Checkov installation
        run: checkov --version

      - name: Run Checkov scan
        run: |
          checkov -d . --output json > checkov-results.json || cat checkov-results.json

      - name: Convert JSON to HTML Table
        uses: Teebra/JSON-to-HTML-table@v2.0.0
        with:
          json-file: checkov-results.json  # Specify the path to your JSON file


      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-iac-report
          path: output.html
