name: trivy

on:
  push:
    branches:
      - main

jobs:
  iac_scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'html'
        output: 'trivy-results.html'
        severity: 'CRITICAL'
    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: checkov-iac-report
        path: trivy-results.html

