name: Snyk Security Scan and Report

on:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install Snyk CLI
    - name: Install Snyk CLI
      run: |
        npm install -g snyk

    # Step 3: Run Snyk test and generate the JSON report
    - name: Run Snyk to check configuration files for security issues
      continue-on-error: true
      run: snyk test --all-projects --json > snyk-report.json

    # Step 4: Convert Snyk JSON report to HTML
    - name: Convert JSON to HTML report
      run: |
        snyk report --format=html --file=snyk-report.json > snyk-report.html

    # Step 5: Upload the HTML report as an artifact
    - name: Upload Snyk HTML report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: snyk-report
        path: snyk-report.html
