name: Snyk Security Scan and Report

on:
  push:
    branches:
      - main
jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install Snyk CLI
    - name: Install Snyk CLI
      run: |
        npm install -g snyk

    # Step 3: Run Snyk test and generate the JSON report
    - name: Run Snyk to check configuration files for security issues
      continue-on-error: true
      run: snyk test --all-projects --sarif > snyk-report.json

    # Step 4: Upload the JSON report as an artifact (optional, for reference)
    - name: Upload Snyk JSON report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: snyk-json-report
        path: snyk-report.json

    # Step 5: Convert the JSON report to HTML format using the Snyk CLI (corrected approach)
    - name: Generate HTML report from Snyk JSON
      run: |
        snyk monitor --file=snyk-report.json  # This sends the report to Snyk’s platform
        snyk report --format=html --file=snyk-report.json > snyk-report.html

    # Step 6: Upload the HTML report as an artifact
    - name: Upload Snyk HTML report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: snyk-html-report
        path: snyk-report.html
