name: Checkov IaC Scan

on:
  push:
    branches:
      - main

jobs:
  checkov-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Checkov
        run: pip install checkov

      - name: Verify Checkov installation
        run: checkov --version

      - name: Run Checkov scan
        run: |
          checkov -d . --output json > checkov-results.json || cat checkov-results.json

      - name: Generate HTML report from JSON
        run: |
          python - <<EOF
          import json
          with open('checkov-results.json') as f:
              results = json.load(f)
          html_content = f"<html><body><h1>Checkov Report</h1><pre>{json.dumps(results, indent=2)}</pre></body></html>"
          with open('checkov-report.html', 'w') as f:
              f.write(html_content)
          EOF


      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-iac-report
          path: checkov-report.html
