name: Snyk Infrastructure as Code

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: ./
      - name: Verify SARIF File
        run: ls -al snyk.sarif
      - name: Display SARIF File
        run: cat snyk.sarif
      - name: Upload SARIF File as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk.sarif
      - name: View SARIF report in HTML
        uses: github/sarif-viewer-action@v2
        with:
          sarif_file: snyk.sarif
