name: Snyk Infrastructure html

on:
  push:
    branches: [ "main" ]

    runs-on: ubuntu-latest
    steps:
  - uses: actions/checkout@v4

  - name: Install Snyk CLI
    run: |
      npm install -g snyk

  - name: Run Snyk to check configuration files for security issues
    continue-on-error: true
    run: snyk test --all-projects --json > snyk-report.json

  - name: Convert Snyk JSON report to HTML
    run: |
      snyk report --format=html --file=snyk-report.json > snyk-report.html

  - name: Upload Snyk HTML report as an artifact
    uses: actions/upload-artifact@v3
    with:
      name: snyk-report
      path: snyk-report.html

