name: Checkov Testing
on:
  push:
    branches:
      - main
jobs:
  checkov_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          # directory: .
          # framework: terraform
          output_format: sarif
          output_file_path: results.sarif

      - name: Console
        run: ls -l

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v3
        
      

      #- name: Install Checkov
      #  run: |
      #   python -m pip install --upgrade pip
      #   pip install checkov  #
      
      #- name: Install Checkov
      #  run: pip install checkov

      #- name: Run Checkov scan
      #  run: |
      #    mkdir -p reports
      #    checkov -d . --quiet --output json > reports/checkov_report.json
      

      #- name: Console
      #  run: ls -l

      
      #- name: Save Checkov Report
      #  run: |
      #    mkdir -p reports
      #    cp results.sarif reports/checkov_report.sarif

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        #with:
        #  projectBaseDir: .
        #  extraArgs: |
        #    -Dsonar.externalIssuesReportPaths=reports.sarif
        #    -Dsonar.inclusions=**/*.tf
        #    -Dsonar.exclusions=**/checkov_reports/**